#!/usr/bin/env bash
# Writes a working Next.js + RainbowKit + wagmi + EOA mint scaffold into WORK_DIR.
# Uses Next.js Pages Router (simpler for hook-heavy web3 code — no "use client" needed).
# Does NOT install packages — caller does that with vendor-specific deps.
#
# Written files:
#   package.json, tsconfig.json, next.config.ts, next-env.d.ts
#   src/pages/_app.tsx         — WagmiProvider + QueryClientProvider + RainbowKitProvider
#   src/pages/index.tsx        — ConnectButton + MintButton when connected
#   src/components/MintButton.tsx — working EOA mint via useWriteContract
#
# NOT written (caller must write):
#   src/lib/config.ts          — vendor-specific (NFT_ABI, NFT_CONTRACT, wagmiConfig, vendor constants)
set -euo pipefail
WORK_DIR="$1"
mkdir -p "$WORK_DIR/src/pages" "$WORK_DIR/src/components" "$WORK_DIR/src/lib"

cat > "$WORK_DIR/package.json" <<'EOF'
{
  "name": "dapp-starter",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  }
}
EOF

cat > "$WORK_DIR/tsconfig.json" <<'EOF'
{
  "compilerOptions": {
    "target": "ES2022",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": false,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "plugins": [{ "name": "next" }]
  },
  "include": ["next-env.d.ts", "src/**/*.ts", "src/**/*.tsx"],
  "exclude": ["node_modules"]
}
EOF

cat > "$WORK_DIR/next.config.ts" <<'EOF'
import type { NextConfig } from "next";
const nextConfig: NextConfig = {};
export default nextConfig;
EOF

# next-env.d.ts is normally generated by `next dev/build`; we create it manually
# so tsc --noEmit works without running Next.js first.
cat > "$WORK_DIR/next-env.d.ts" <<'EOF'
/// <reference types="next" />
/// <reference types="next/image-types/global" />
EOF

# _app.tsx — providers wrapper (equivalent of main.tsx in Vite)
cat > "$WORK_DIR/src/pages/_app.tsx" <<'EOF'
import type { AppProps } from "next/app";
import { WagmiProvider } from "wagmi";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { RainbowKitProvider } from "@rainbow-me/rainbowkit";
import { wagmiConfig } from "../lib/config";

const queryClient = new QueryClient();

export default function App({ Component, pageProps }: AppProps) {
  return (
    <WagmiProvider config={wagmiConfig}>
      <QueryClientProvider client={queryClient}>
        <RainbowKitProvider>
          <Component {...pageProps} />
        </RainbowKitProvider>
      </QueryClientProvider>
    </WagmiProvider>
  );
}
EOF

# index.tsx — main page
cat > "$WORK_DIR/src/pages/index.tsx" <<'EOF'
import { ConnectButton } from "@rainbow-me/rainbowkit";
import { useAccount } from "wagmi";
import { MintButton } from "../components/MintButton";

export default function Home() {
  const { isConnected } = useAccount();
  return (
    <div>
      <h1>dApp Starter</h1>
      <ConnectButton />
      {isConnected && <MintButton />}
    </div>
  );
}
EOF

# MintButton.tsx — working EOA mint; agent upgrades this to use vendor's smart account stack
cat > "$WORK_DIR/src/components/MintButton.tsx" <<'EOF'
import { useState } from "react";
import { useAccount, useWriteContract } from "wagmi";
import { NFT_ABI, NFT_CONTRACT } from "../lib/config";

export function MintButton() {
  const { address } = useAccount();
  const { writeContract, isPending, data: hash, error } = useWriteContract();

  const handleMint = () => {
    if (!address) return;
    writeContract({
      address: NFT_CONTRACT,
      abi: NFT_ABI,
      functionName: "mint",
      args: [address],
    });
  };

  return (
    <div>
      <button onClick={handleMint} disabled={isPending}>
        {isPending ? "Minting…" : "Mint NFT"}
      </button>
      {hash && <p>Minted! tx: {hash}</p>}
      {error && <p>Error: {error.message}</p>}
    </div>
  );
}
EOF
